apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget_calculations-deploy
  labels:
    name: budget_calculations-deploy
    app: budget_calculations-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: budget_calculations-pod
      app: budget_calculations-app

  template:
    metadata:
      name: budget_calculations-pod
      labels:
        name: budget_calculations-pod
        app: budget_calculations-app
    spec:
      containers:
        - name: budget_calculations
          image: elmseldh/budget_calculations
          ports:
            - containerPort: 80
